name       : megatools
version    : 1.10.2
release    : 2
source     :
    - https://megatools.megous.com/builds/megatools-1.10.2.tar.gz : 179e84c68e24696c171238a72bcfe5e28198e4c4e9f9043704f36e5c0b17c38a
license    : GPL-2.0-or-later
component  : network.download
homepage   : https://megatools.megous.com/
summary    : Command line tools for accessing MEGA cloud storage
description: |
    Megatools is a collection of programs for accessing Mega service from the command line. It
    allows you to copy individual files as well as entire directory trees to and from the cloud.
    You can also perform streaming downloads without needing to download the entire file.
builddeps  :
    - pkgconfig(libcurl)
    - asciidoc
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
