name       : megatools
version    : 1.10.2
release    : 3
source     :
    - https://github.com/megous/megatools/archive/1.10.2.tar.gz : 48468536492bfecd8b10a42e7608129eba9922e03cbce0a11dd9e338e2a0632d
license    : GPL-2.0-or-later
component  : network.download
homepage   : https://megatools.megous.com/
summary    : Command line tools for accessing MEGA cloud storage
description: |
    Megatools is a collection of programs for accessing Mega service from the command line. It
    allows you to copy individual files as well as entire directory trees to and from the cloud.
    You can also perform streaming downloads without needing to download the entire file.
builddeps  :
    - pkgconfig(libcurl)
    - asciidoc
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
